name: Automate publish nuget packages

# Auto build every day at 00:00
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  # Job name
  build-nupkg:
    # Run on windows
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Download and pack .nupkg
      run: .\build.ps1 -FetchVersionFromNuget
    - name: Set nuget api key
      run: utils/nuget.exe setapikey ${{secrets.NUGET_KEY}}
    - name: Publish to nuget
      run: .\publish.ps1
