name: Autobuild .cab test

# Auto build every day at 00:00
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  # Job name
  build-cab:
    # Run on windows
    runs-on: windows-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Run download command
      run: .\build.ps1 -FetchVersionFromNuget
    - name: Collect result
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: ${{ github.workspace }}\*.nupkg
    - name: Publish to nuget
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path: './*.nupkg'
        repo-owner: 'ProKn1fe'
        gh-user: 'ProKn1fe'
        token:  ${{ secrets.NUGET_KEY }}
